POST http://localhost:5241/webservice/v1/api/auth/register
Content-Type: application/json

{
    "name": "Karun Ghimire",
    "email": "ghimirekarun408@gmail.com",
    "password": "kArun@123",
    "username": "karun2025",
    "phone": "9840418283"
}